In [1]:
import pandas as pd

# Load the uploaded Excel file to check its structure
file_path = '../dataset/rab107row.xlsx'
data = pd.read_excel(file_path)

# Display the first few rows to understand the structure
data.head()

,namaproyek,rab,waktu,provinsi,tahun,luas,subitem,tinggi,lantai,ikk,ihbp,inflasi
0,Gedung Apartemen,2.641914e+10,196,Jawa Barat,2019,17401.00,4,21.8,6,103.03,143.72,3.21
1,Gedung Apartemen,8.821079e+10,273,DKI Jakarta,2022,16320.59,6,47.6,14,121.48,107.66,4.21
2,Gedung Apartemen,8.171200e+10,348,DKI Jakarta,2023,23688.00,5,34.0,10,116.73,113.88,2.28
3,Gedung Apartemen,3.690000e+11,830,Banten,2021,55000.00,6,49.8,16,97.64,109.64,1.91
4,Gedung Apartemen,5.400316e+11,700,DKI Jakarta,2023,150000.00,6,105.0,30,116.73,113.88,2.28

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import BayesianRidge, Lasso, LinearRegression, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
import xgboost as xgb
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

In [3]:
# 6. One-Hot Encoding untuk 'provinsi' dan 'namaproyek'
data = pd.get_dummies(data, columns=['namaproyek', 'provinsi'])

In [4]:
data.head()

,rab,waktu,tahun,luas,subitem,tinggi,lantai,ikk,ihbp,inflasi,...,provinsi_DKI Jakarta,provinsi_Jawa Barat,provinsi_Jawa Tengah,provinsi_Jawa Timur,provinsi_Kalimantan Timur,provinsi_Kepulauan Riau,provinsi_Lampung,provinsi_Nusa Tenggara Barat,provinsi_Papua,provinsi_Sulawesi Selatan
0,2.641914e+10,196,2019,17401.00,4,21.8,6,103.03,143.72,3.21,...,False,True,False,False,False,False,False,False,False,False
1,8.821079e+10,273,2022,16320.59,6,47.6,14,121.48,107.66,4.21,...,True,False,False,False,False,False,False,False,False,False
2,8.171200e+10,348,2023,23688.00,5,34.0,10,116.73,113.88,2.28,...,True,False,False,False,False,False,False,False,False,False
3,3.690000e+11,830,2021,55000.00,6,49.8,16,97.64,109.64,1.91,...,False,False,False,False,False,False,False,False,False,False
4,5.400316e+11,700,2023,150000.00,6,105.0,30,116.73,113.88,2.28,...,True,False,False,False,False,False,False,False,False,False

In [4]:
# Split data into features and target
X1 = data.drop(columns=['rab'])
y1 = data['rab']

# Split into training and testing sets
X_train1, X_test1, y_train1, y_test1 = train_test_split(
    X1, y1, 
    test_size=0.3, 
    random_state=42)

# Split into training and testing sets
X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X1, y1, 
    test_size=0.2, 
    random_state=42)

In [5]:
# Initialize models
models = {
    'AdaBoost': AdaBoostRegressor(),
    'Bayesian Ridge': BayesianRidge(),
    'Decision Tree': DecisionTreeRegressor(),
    'Gradient Boosting': GradientBoostingRegressor(),
    'KNN Regressor': KNeighborsRegressor(),
    'Lasso Regression': Lasso(),
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(),
    'Ridge Regression': Ridge(),
    'SVR': SVR(),
    'XGBoost': xgb.XGBRegressor()
}

# 70:30
# Train and evaluate each model with additional metrics
results1 = []
for name1, model1 in models.items():
    # Fit model to training data
    model1.fit(X_train1, y_train1)
    
    # Predict on training data
    y_train_pred1 = model1.predict(X_train1)
    
    # Predict on testing data
    y_pred1 = model1.predict(X_test1)
    
    # Calculate metrics for training data
    r2_train1 = r2_score(y_train1, y_train_pred1)
    
    # Calculate metrics for testing data
    mse1 = mean_squared_error(y_test1, y_pred1)
    mae1 = mean_absolute_error(y_test1, y_pred1)
    r21 = r2_score(y_test1, y_pred1)
    
    # Append results
    results1.append({
        'Model': name1,
        'Training R2 Score': r2_train1,
        'Testing RMSE': np.sqrt(mse1),
        'Testing MAE': mae1,
        'Testing R2 Score': r21
    })

# Convert results into a DataFrame for better visualization
results_df1 = pd.DataFrame(results1).sort_values(by='Testing R2 Score', ascending=False)

# 80:20
# Train and evaluate each model with additional metrics
results2 = []
for name2, model2 in models.items():
    # Fit model to training data
    model2.fit(X_train2, y_train2)
    
    # Predict on training data
    y_train_pred2 = model2.predict(X_train2)
    
    # Predict on testing data
    y_pred2 = model2.predict(X_test2)
    
    # Calculate metrics for training data
    r2_train2 = r2_score(y_train2, y_train_pred2)
    
    # Calculate metrics for testing data
    mse2 = mean_squared_error(y_test2, y_pred2)
    mae2 = mean_absolute_error(y_test2, y_pred2)
    r22 = r2_score(y_test2, y_pred2)
    
    # Append results
    results2.append({
        'Model': name2,
        'Training R2 Score': r2_train2,
        'Testing RMSE': np.sqrt(mse2),
        'Testing MAE': mae2,
        'Testing R2 Score': r22
    })

# Convert results into a DataFrame for better visualization
results_df2 = pd.DataFrame(results2).sort_values(by='Testing R2 Score', ascending=False)

c:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.162e+24, tolerance: 1.095e+21
  model = cd_fast.enet_coordinate_descent(
c:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.398e+24, tolerance: 1.116e+21
  model = cd_fast.enet_coordinate_descent(

Hasil 70:30

In [6]:
results_df1

,Model,Training R2 Score,Testing RMSE,Testing MAE,Testing R2 Score
3,Gradient Boosting,9.992779e-01,6.036005e+11,2.120894e+11,0.397987
7,Random Forest,8.746062e-01,6.718784e+11,1.947893e+11,0.254087
4,KNN Regressor,3.488220e-01,6.781555e+11,2.108000e+11,0.240085
8,Ridge Regression,7.735860e-01,6.787599e+11,2.308528e+11,0.238730
6,Linear Regression,7.876641e-01,6.968857e+11,2.374626e+11,0.197528
5,Lasso Regression,7.876641e-01,6.981939e+11,2.418069e+11,0.194513
0,AdaBoost,9.677269e-01,6.986438e+11,2.083798e+11,0.193474
1,Bayesian Ridge,7.120970e-13,7.825614e+11,2.626198e+11,-0.011914
2,Decision Tree,1.000000e+00,7.949583e+11,2.395733e+11,-0.044228
9,SVR,-8.377046e-02,8.023121e+11,2.381101e+11,-0.063637
10,XGBoost,1.000000e+00,9.112059e+11,2.781956e+11,-0.371954

Hasil 80:20

In [7]:
results_df2

,Model,Training R2 Score,Testing RMSE,Testing MAE,Testing R2 Score
4,KNN Regressor,3.882603e-01,8.060858e+11,2.573474e+11,0.268514
8,Ridge Regression,7.302853e-01,8.505666e+11,2.682102e+11,0.185559
7,Random Forest,9.098887e-01,8.558199e+11,2.555049e+11,0.175467
6,Linear Regression,7.472063e-01,8.699429e+11,2.698134e+11,0.148029
5,Lasso Regression,7.472063e-01,8.716757e+11,2.739151e+11,0.144632
0,AdaBoost,9.457109e-01,9.068162e+11,2.858711e+11,0.074275
3,Gradient Boosting,9.986625e-01,9.252372e+11,2.893059e+11,0.036283
1,Bayesian Ridge,9.157120e-13,9.540874e+11,3.320020e+11,-0.024754
2,Decision Tree,1.000000e+00,9.545266e+11,3.238198e+11,-0.025698
9,SVR,-8.530357e-02,9.761482e+11,2.999610e+11,-0.072691
10,XGBoost,1.000000e+00,1.112785e+12,3.985262e+11,-0.394010